```yaml
name: Self Hosted Runner Test

on:
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Check computer
        shell: cmd
        run: hostname

      - name: Check Docker version
        shell: cmd
        run: '"C:\Users\DELL\AppData\Local\Programs\DockerDesktop\resources\bin\docker.exe" --version'

      - name: Check running containers
        shell: cmd
        run: '"C:\Users\DELL\AppData\Local\Programs\DockerDesktop\resources\bin\docker.exe" ps'

      - name: Check Python
        shell: cmd
        run: python --version
```
